package ru.pnecrome;

/** Сгенерировано из tools/hybrids.txt (tools/gen_tables.py). Не править вручную.
 *  Каждая строка: id | донор части | часть | (base не задан — гибрид строится по жертве) | имя RU | имя EN | статы. */
public class HybridTable {

    public static void populate(HybridRegistry.Sink sink) {
        sink.add("revenant", "minecraft:zombie", "head", "", "Ревенант", "Revenant", 1.50, 1.00, 1.50, false, "Ожившая голова зомби: бьёт жадно и не знает покоя.");
        sink.add("graspulo", "minecraft:zombie", "arms", "", "Хватун", "Graspulo", 1.00, 1.00, 1.50, false, "Руки зомби хватают мёртвой хваткой.");
        sink.add("shambler", "minecraft:zombie", "legs", "", "Хромоступ", "Shambler", 1.00, 0.90, 1.00, false, "Походку ходячего мертвеца не остановить.");
        sink.add("carrionkin", "minecraft:zombie", "torso", "", "Мертвецовина", "Carrionkin", 1.50, 1.00, 1.00, false, "Туша, что кормит сама себя.");
        sink.add("miasma", "minecraft:creeper", "head", "", "Миазма", "Miasma", 1.00, 1.10, 1.00, false, "Шипящий череп, пропитанный порохом.");
        sink.add("fusearm", "minecraft:creeper", "arms", "", "Детонатор", "Fusearm", 1.00, 1.00, 1.00, false, "Обнимает — и шипит.");
        sink.add("hissstride", "minecraft:creeper", "legs", "", "Шипоход", "Hissstride", 1.00, 1.20, 1.00, false, "Крадётся, тихо шипя на каждый шаг.");
        sink.add("blisterhide", "minecraft:creeper", "torso", "", "Пузырешкура", "Blisterhide", 1.00, 1.00, 1.00, false, "Кожа вздулась порохом.");
        sink.add("bonewraith", "minecraft:skeleton", "head", "", "Костяной призрак", "Bonewraith", 1.00, 1.00, 1.00, false, "Пустой череп, в котором горит холодный огонь.");
        sink.add("bonewrist", "minecraft:skeleton", "arms", "", "Кистекость", "Bonewrist", 1.00, 1.00, 1.00, false, "Ловкий запястный хват из чистых костей.");
        sink.add("boneshanks", "minecraft:skeleton", "legs", "", "Костоплёт", "Boneshanks", 1.00, 1.20, 1.00, false, "Стучат в гроб изнутри.");
        sink.add("ribcage", "minecraft:skeleton", "torso", "", "Реброклон", "Ribcage", 1.00, 1.00, 1.00, false, "Грудная клетка, созвучная арфе смерти.");
        sink.add("weaver", "minecraft:spider", "head", "", "Ткач", "Weaver", 1.00, 1.20, 1.00, false, "Восемь глаз смотрят из-под савана.");
        sink.add("legsworn", "minecraft:spider", "arms", "", "Паучелап", "Legsworn", 1.00, 1.10, 1.00, false, "Восемь рук вместо двух.");
        sink.add("skitterling", "minecraft:spider", "legs", "", "Скиттерлинг", "Skitterling", 1.00, 1.50, 1.00, false, "Восемь шагов на один вдох.");
        sink.add("fuzzback", "minecraft:spider", "torso", "", "Пухоспин", "Fuzzback", 1.00, 1.00, 1.00, false, "Мохнатая спина выползает из щели.");
        sink.add("venomweaver", "minecraft:cave_spider", "head", "", "Ядовитый ткач", "Venomweaver", 1.00, 1.20, 1.00, false, "Его взгляд обжигает плоть ядом.");
        sink.add("venomclutch", "minecraft:cave_spider", "arms", "", "Ядохват", "Venomclutch", 1.00, 1.00, 1.00, false, "Обнимает и заражает.");
        sink.add("creepskitter", "minecraft:cave_spider", "legs", "", "Ползунок", "Creepskitter", 1.00, 1.40, 1.00, false, "Тихо крадётся по стенам.");
        sink.add("greenscab", "minecraft:cave_spider", "torso", "", "Зелёная парша", "Greenscab", 1.00, 1.00, 1.00, false, "Бока, сочащиеся ядом.");
        sink.add("hollow", "minecraft:enderman", "head", "", "Пустотелый", "Hollow", 1.50, 1.10, 1.50, false, "Не смотрите ему в глаза... если они ещё есть.");
        sink.add("voidreach", "minecraft:enderman", "arms", "", "Пустотомах", "Voidreach", 1.00, 1.00, 1.50, false, "Достаёт оттуда, откуда не возвращаются.");
        sink.add("longstride", "minecraft:enderman", "legs", "", "Дальноход", "Longstride", 1.00, 1.50, 1.00, false, "Шаг — и его уже нет.");
        sink.add("portalhide", "minecraft:enderman", "torso", "", "Портальник", "Portalhide", 1.50, 1.00, 1.00, false, "В рёбрах его груди гаснут миры.");
        sink.add("emberwight", "minecraft:blaze", "head", "", "Уголёк", "Emberwight", 1.00, 1.00, 1.50, true, "Тлеющий череп из загробного пламени.");
        sink.add("embergrasp", "minecraft:blaze", "arms", "", "Углохват", "Embergrasp", 1.00, 1.00, 1.50, true, "Рукавицы из жара.");
        sink.add("firewalk", "minecraft:blaze", "legs", "", "Огнеход", "Firewalk", 1.00, 1.20, 1.00, true, "Стебли пламени вместо ног.");
        sink.add("cinderchest", "minecraft:blaze", "torso", "", "Углескул", "Cinderchest", 1.00, 1.00, 1.00, true, "Грудная клетка из пылающих прутьев.");
        sink.add("hexling", "minecraft:witch", "head", "", "Ведьмёныш", "Hexling", 1.00, 1.00, 1.00, false, "Маленький наводчик порчи.");
        sink.add("cauldronarms", "minecraft:witch", "arms", "", "Котелкорук", "Cauldronarms", 1.00, 1.00, 1.00, false, "Мешает варево из теней.");
        sink.add("hextrip", "minecraft:witch", "legs", "", "Ведрога", "Hextrip", 1.00, 1.10, 1.00, false, "Спотыкаешься там, где она прошла.");
        sink.add("brewhide", "minecraft:witch", "torso", "", "Варешкура", "Brewhide", 1.00, 1.00, 1.00, false, "Пахнет полынью и серой.");
        sink.add("curseling", "minecraft:villager", "head", "", "Проклятор", "Curseling", 1.00, 1.00, 1.00, false, "Житель, чья душа осталась в трупе.");
        sink.add("traderhands", "minecraft:villager", "arms", "", "Торговец", "Traderhands", 1.00, 1.00, 1.00, false, "Продаёт то, чего нет.");
        sink.add("marketstrider", "minecraft:villager", "legs", "", "Базарник", "Marketstrider", 1.00, 1.10, 1.00, false, "Ходит рядами пустых лавок.");
        sink.add("toadycloth", "minecraft:villager", "torso", "", "Ряба", "Toadycloth", 1.00, 1.00, 1.00, false, "Роба торговца, снятая с живого.");
        sink.add("dreadnought", "minecraft:iron_golem", "head", "", "Грозобор", "Dreadnought", 2.00, 0.90, 1.50, false, "Железная голова, что помнит долг стража.");
        sink.add("ironmaul", "minecraft:iron_golem", "arms", "", "Железнобой", "Ironmaul", 2.00, 0.90, 2.00, false, "Удар молота из кованого металла.");
        sink.add("bulwark", "minecraft:iron_golem", "legs", "", "Бастион", "Bulwark", 2.00, 0.80, 1.00, false, "Ноги из крепостной стены.");
        sink.add("platebelly", "minecraft:iron_golem", "torso", "", "Брюхолит", "Platebelly", 2.00, 1.00, 1.00, false, "Живот из клёпаного железа.");
        sink.add("grunkgul", "minecraft:pig", "head", "", "Хрюкогуль", "Grunkgul", 1.00, 1.00, 1.00, false, "Хрюкает из-за гроба и всё ещё ведёт на убой.");
        sink.add("trotterarms", "minecraft:pig", "arms", "", "Копытерук", "Trotterarms", 1.00, 1.00, 1.00, false, "Копыта вместо ладоней.");
        sink.add("trotter", "minecraft:pig", "legs", "", "Бегоножка", "Trotter", 1.00, 1.30, 1.00, false, "Трусит к бойне сама.");
        sink.add("baconhide", "minecraft:pig", "torso", "", "Салошкура", "Baconhide", 1.00, 1.00, 1.00, false, "Сало, что не берёт нож.");
        sink.add("mooreshade", "minecraft:cow", "head", "", "Мычатень", "Mooreshade", 1.00, 1.00, 1.00, false, "Тень рогатого пастбища.");
        sink.add("milktouch", "minecraft:cow", "arms", "", "Молокоперст", "Milktouch", 1.00, 1.00, 1.00, false, "Ласковое доитьё.");
        sink.add("taurokk", "minecraft:cow", "legs", "", "Таурокк", "Taurokk", 1.50, 1.20, 1.00, false, "Бычьи ноги несут быстрее боли.");
        sink.add("beefside", "minecraft:cow", "torso", "", "Говядобок", "Beefside", 1.00, 1.00, 1.00, false, "Сочное мясо, что не портится.");
        sink.add("fleeceghast", "minecraft:sheep", "head", "", "Рунопризрак", "Fleeceghast", 1.00, 1.00, 1.00, false, "Шерсть, что шевелится сама.");
        sink.add("fleecemittens", "minecraft:sheep", "arms", "", "Шерстолапка", "Fleecemittens", 1.00, 1.00, 1.00, false, "Мягкие, но цепкие.");
        sink.add("woolwalker", "minecraft:sheep", "legs", "", "Шерстеход", "Woolwalker", 1.00, 1.10, 1.00, false, "Топает мягко, как снег.");
        sink.add("fleecybod", "minecraft:sheep", "torso", "", "Рунобрюх", "Fleecybod", 1.00, 1.00, 1.00, false, "Брюхо тёплое, как могила зимой.");
        sink.add("clatterhen", "minecraft:chicken", "head", "", "Клакуша", "Clatterhen", 1.00, 1.20, 1.00, false, "Несёт только яйца из костей.");
        sink.add("wingreach", "minecraft:chicken", "arms", "", "Крылкорук", "Wingreach", 1.00, 1.00, 1.00, false, "Крылья вместо рук.");
        sink.add("scratchling", "minecraft:chicken", "legs", "", "Царапун", "Scratchling", 1.00, 1.30, 1.00, false, "Роет могилы когтями.");
        sink.add("featherpelt", "minecraft:chicken", "torso", "", "Перешкур", "Featherpelt", 1.00, 1.00, 1.00, false, "Щипаная тушка, что встала сама.");
        sink.add("nightmare", "minecraft:horse", "head", "", "Кошмар", "Nightmare", 1.00, 1.30, 1.00, false, "Скачет там, где нет дороги.");
        sink.add("hoofgauntlet", "minecraft:horse", "arms", "", "Кованорука", "Hoofgauntlet", 1.00, 1.00, 1.00, false, "Подкова в кулаке.");
        sink.add("striderspawn", "minecraft:horse", "legs", "", "Странник", "Striderspawn", 1.00, 1.50, 1.00, false, "Копыта, что не знают устали.");
        sink.add("barrelbred", "minecraft:horse", "torso", "", "Бочкогрив", "Barrelbred", 1.00, 1.00, 1.00, false, "Широкая грудь для скачки в вечность.");
        sink.add("grimfang", "minecraft:wolf", "head", "", "Мрачнозуб", "Grimfang", 1.00, 1.20, 1.50, false, "Верный пёс даже после смерти.");
        sink.add("clutchjaw", "minecraft:wolf", "arms", "", "Хваткогель", "Clutchjaw", 1.00, 1.00, 1.50, false, "Держит мёртвой хваткой.");
        sink.add("dashhound", "minecraft:wolf", "legs", "", "Погонщик", "Dashhound", 1.00, 1.50, 1.00, false, "Догоняет даже убегающую жизнь.");
        sink.add("sheltere", "minecraft:wolf", "torso", "", "Шерстозвер", "Sheltere", 1.00, 1.00, 1.00, false, "Грубая шерсть сторожевого пса.");
        sink.add("shadowprowler", "minecraft:ocelot", "head", "", "Тенеброд", "Shadowprowler", 1.00, 1.30, 1.00, false, "Бесшумный охотник сумрака.");
        sink.add("softtalons", "minecraft:ocelot", "arms", "", "Мягкий коготь", "Softtalons", 1.00, 1.00, 1.00, false, "Царапает без звука.");
        sink.add("silkpaw", "minecraft:ocelot", "legs", "", "Шелколап", "Silkpaw", 1.00, 1.50, 1.00, false, "Лапа тише шёлка.");
        sink.add("junglecoat", "minecraft:ocelot", "torso", "", "Джунглеплащ", "Junglecoat", 1.00, 1.00, 1.00, false, "Пятнистая шкура джунглей.");
        sink.add("nineveil", "minecraft:cat", "head", "", "Девятизавес", "Nineveil", 1.00, 1.20, 1.00, false, "Все девять жизней ушли в тенета.");
        sink.add("silkscratch", "minecraft:cat", "arms", "", "Шелкодрать", "Silkscratch", 1.00, 1.00, 1.00, false, "Оставляет пять борозд.");
        sink.add("velvetclaw", "minecraft:cat", "legs", "", "Бархатный коготь", "Velvetclaw", 1.00, 1.50, 1.00, false, "Приземляется всегда на ту сторону.");
        sink.add("ashpelt", "minecraft:cat", "torso", "", "Пеплошкура", "Ashpelt", 1.00, 1.00, 1.00, false, "Серая шерсть, пахнущая гарью.");
        sink.add("ramshorn", "minecraft:goat", "head", "", "Рогочаст", "Ramshorn", 1.00, 1.10, 1.50, false, "Бодает призрачные горы.");
        sink.add("ramshoulder", "minecraft:goat", "arms", "", "Баранье плечо", "Ramshoulder", 1.00, 1.00, 1.50, false, "Плечо, что сносит двери.");
        sink.add("scraphooves", "minecraft:goat", "legs", "", "Сквозкопыт", "Scraphooves", 1.00, 1.30, 1.00, false, "Бьёт копытом о камень склепа.");
        sink.add("mountainmane", "minecraft:goat", "torso", "", "Горногрив", "Mountainmane", 1.00, 1.00, 1.00, false, "Грива, пахнущая камнем и солью.");
        sink.add("bamboogul", "minecraft:panda", "head", "", "Бамбукогуль", "Bamboogul", 1.50, 0.90, 1.00, false, "Сонный гигант бамбуковых склепов.");
        sink.add("bamboohug", "minecraft:panda", "arms", "", "Бамбуконятие", "Bamboohug", 1.50, 1.00, 1.00, false, "Объятия тяжёлые, как ствол.");
        sink.add("reedshambler", "minecraft:panda", "legs", "", "Тростник-ходунок", "Reedshambler", 1.00, 0.90, 1.00, false, "Идёт медленно, но верно.");
        sink.add("bambooloam", "minecraft:panda", "torso", "", "Бамбукслизь", "Bambooloam", 1.50, 1.00, 1.00, false, "Толокно из сонной бамбуковой пыли.");
        sink.add("vulpine", "minecraft:fox", "head", "", "Лисолюд", "Vulpine", 1.00, 1.30, 1.00, false, "Хитёр и после погоста.");
        sink.add("slypaws", "minecraft:fox", "arms", "", "Лиселипы", "Slypaws", 1.00, 1.00, 1.00, false, "Крадёт из-под носа.");
        sink.add("quickvein", "minecraft:fox", "legs", "", "Быстрожил", "Quickvein", 1.00, 1.40, 1.00, false, "Лисий бег по тонкому льду.");
        sink.add("emberfur", "minecraft:fox", "torso", "", "Уголемех", "Emberfur", 1.00, 1.00, 1.00, false, "Рыжий мех, тлеющий изнутри.");
        sink.add("stinger", "minecraft:bee", "head", "", "Жалинг", "Stinger", 1.00, 1.20, 1.00, false, "Жужжание из-под земли.");
        sink.add("stingarms", "minecraft:bee", "arms", "", "Жалкорук", "Stingarms", 1.00, 1.00, 1.00, false, "Обнимает и жалит.");
        sink.add("pollenghast", "minecraft:bee", "legs", "", "Пыльцемер", "Pollenghast", 1.00, 1.30, 1.00, false, "Собирает пыль с надгробий.");
        sink.add("fuzzbum", "minecraft:bee", "torso", "", "Пухозад", "Fuzzbum", 1.00, 1.00, 1.00, false, "Пушистый зад, гудящий на весь улей.");
        sink.add("tidesoul", "minecraft:dolphin", "head", "", "Приливник", "Tidesoul", 1.00, 1.20, 1.00, false, "Дельфин, заплывший в мир мёртвых.");
        sink.add("flippergrasp", "minecraft:dolphin", "arms", "", "Ластохват", "Flippergrasp", 1.00, 1.00, 1.00, false, "Ласты, что топят.");
        sink.add("swiftcurrent", "minecraft:dolphin", "legs", "", "Быстротечение", "Swiftcurrent", 1.00, 1.40, 1.00, false, "Течёт против смерти.");
        sink.add("waveside", "minecraft:dolphin", "torso", "", "Волнобок", "Waveside", 1.00, 1.00, 1.00, false, "Гладкий бок, режущий волну.");
        sink.add("gillfiend", "minecraft:axolotl", "head", "", "Жабролюд", "Gillfiend", 1.00, 1.10, 1.00, false, "Улыбается, даже будучи мертвецом.");
        sink.add("gillhold", "minecraft:axolotl", "arms", "", "Жаброхват", "Gillhold", 1.00, 1.00, 1.00, false, "Хватает за жабры.");
        sink.add("marshskipper", "minecraft:axolotl", "legs", "", "Топебол", "Marshskipper", 1.00, 1.20, 1.00, false, "Перебирается через топи.");
        sink.add("gillmass", "minecraft:axolotl", "torso", "", "Жаберник", "Gillmass", 1.00, 1.00, 1.00, false, "Пучок алых жабр на боку.");
        sink.add("shellwarden", "minecraft:turtle", "head", "", "Панцирник", "Shellwarden", 1.50, 0.80, 1.00, false, "Дом, который пережил хозяина.");
        sink.add("flippershield", "minecraft:turtle", "arms", "", "Ластощит", "Flippershield", 1.50, 1.00, 1.00, false, "Отбивает удары панцирем.");
        sink.add("tidecrawler", "minecraft:turtle", "legs", "", "Приливополз", "Tidecrawler", 1.00, 0.90, 1.00, false, "Ползёт к морю мертвецов.");
        sink.add("scuteplate", "minecraft:turtle", "torso", "", "Щитоспин", "Scuteplate", 1.50, 1.00, 1.00, false, "Панцирные пластины старого моряка.");
        sink.add("scalespawn", "minecraft:cod", "head", "", "Чешуйник", "Scalespawn", 1.00, 1.00, 1.00, false, "Мелкая рыбья нежить.");
        sink.add("finclasp", "minecraft:cod", "arms", "", "Плавнехват", "Finclasp", 1.00, 1.00, 1.00, false, "Скользкий захват.");
        sink.add("finsteps", "minecraft:cod", "legs", "", "Плавненога", "Finsteps", 1.00, 1.10, 1.00, false, "Плавает по суше, как по воде.");
        sink.add("silverflank", "minecraft:cod", "torso", "", "Серебробок", "Silverflank", 1.00, 1.00, 1.00, false, "Чешуя блестит, как монета утопленника.");
        sink.add("runsire", "minecraft:salmon", "head", "", "Нерестник", "Runsire", 1.00, 1.00, 1.00, false, "Идёт против течения смерти.");
        sink.add("rivergrab", "minecraft:salmon", "arms", "", "Речной захват", "Rivergrab", 1.00, 1.00, 1.00, false, "Тянет в воду.");
        sink.add("riverdash", "minecraft:salmon", "legs", "", "Речной бегун", "Riverdash", 1.00, 1.30, 1.00, false, "Прыгает через плотину стужи.");
        sink.add("runside", "minecraft:salmon", "torso", "", "Нерестебок", "Runside", 1.00, 1.00, 1.00, false, "Бока красные от дальней дороги.");
        sink.add("coralgul", "minecraft:tropical_fish", "head", "", "Коралкогуль", "Coralgul", 1.00, 1.00, 1.00, false, "Яркий, как закат над могилой.");
        sink.add("coralgrasp", "minecraft:tropical_fish", "arms", "", "Кораллохват", "Coralgrasp", 1.00, 1.00, 1.00, false, "Царапает, как риф.");
        sink.add("reefling", "minecraft:tropical_fish", "legs", "", "Рифлик", "Reebling", 1.00, 1.10, 1.00, false, "Пёстрый малёк глубин.");
        sink.add("reefbelly", "minecraft:tropical_fish", "torso", "", "Рифопуз", "Reefbelly", 1.00, 1.00, 1.00, false, "Расписное брюхо тёплых вод.");
        sink.add("bloatling", "minecraft:pufferfish", "head", "", "Надутыш", "Bloatling", 1.00, 1.00, 1.00, false, "Надувается от собственного яда.");
        sink.add("spikehug", "minecraft:pufferfish", "arms", "", "Колючие объятья", "Spikehug", 1.00, 1.00, 1.00, false, "Обнимешь — пожалеешь.");
        sink.add("spikestand", "minecraft:pufferfish", "legs", "", "Колючестое", "Spikestand", 1.00, 0.90, 1.00, false, "Стоит на иголках.");
        sink.add("bloatbod", "minecraft:pufferfish", "torso", "", "Раздутень", "Bloatbod", 1.00, 1.00, 1.00, false, "Надутое тело, полное воздуха и яда.");
        sink.add("capghast", "minecraft:mooshroom", "head", "", "Шляпопризрак", "Capghast", 1.00, 1.00, 1.00, false, "Грибница, проросшая сквозь череп.");
        sink.add("capembrace", "minecraft:mooshroom", "arms", "", "Шляпопонятие", "Capembrace", 1.00, 1.00, 1.00, false, "Тепло гнилых грибов.");
        sink.add("myceliamble", "minecraft:mooshroom", "legs", "", "Грибоход", "Myceliamble", 1.00, 1.00, 1.00, false, "За ним растёт грибница.");
        sink.add("shroomhide", "minecraft:mooshroom", "torso", "", "Грибошкура", "Shroomhide", 1.00, 1.00, 1.00, false, "Кожа, усеянная шляпками мухоморов.");
        sink.add("inkshade", "minecraft:squid", "head", "", "Чернильник", "Inkshade", 1.00, 1.00, 1.00, false, "Окрашивает туман в чёрный.");
        sink.add("tentaclemass", "minecraft:squid", "arms", "", "Щупальщик", "Tentaclemass", 1.00, 1.00, 1.00, false, "Опутывает всего.");
        sink.add("tentaclelimb", "minecraft:squid", "legs", "", "Щупаленог", "Tentaclelimb", 1.00, 1.10, 1.00, false, "Хватает за ногу из темноты.");
        sink.add("blackbile", "minecraft:squid", "torso", "", "Черножелчь", "Blackbile", 1.00, 1.00, 1.00, false, "Мешочки с чернилами под рёбрами.");
        sink.add("lanternsquid", "minecraft:glow_squid", "head", "", "Фонароголь", "Lanternsquid", 1.00, 1.00, 1.00, false, "Свет маяка для заблудших душ.");
        sink.add("lampclutch", "minecraft:glow_squid", "arms", "", "Светохват", "Lampclutch", 1.00, 1.00, 1.00, false, "Светящиеся наручники.");
        sink.add("glowtentacle", "minecraft:glow_squid", "legs", "", "Светощуп", "Glowtentacle", 1.00, 1.10, 1.00, false, "Фонари из щупалец.");
        sink.add("lumenbelly", "minecraft:glow_squid", "torso", "", "Светопуз", "Lumenbelly", 1.00, 1.00, 1.00, false, "Брюхо, светящееся в толще воды.");
        sink.add("nightwing", "minecraft:bat", "head", "", "Ночнокрыл", "Nightwing", 1.00, 1.20, 1.00, false, "Крик летучей мыши из склепа.");
        sink.add("batwingarms", "minecraft:bat", "arms", "", "Нетопылерук", "Batwingarms", 1.00, 1.00, 1.00, false, "Обвивает, как плащ.");
        sink.add("roosthang", "minecraft:bat", "legs", "", "Нетылыш", "Roosthang", 1.00, 1.20, 1.00, false, "Висит вниз головой вечно.");
        sink.add("hangpelt", "minecraft:bat", "torso", "", "Подвесшкур", "Hangpelt", 1.00, 1.00, 1.00, false, "Шкурка, привыкшая висеть вверх ногами.");
        sink.add("plumeclaw", "minecraft:parrot", "head", "", "Пернокоть", "Plumeclaw", 1.00, 1.10, 1.00, false, "Повторяет последние слова умерших.");
        sink.add("feathergrip", "minecraft:parrot", "arms", "", "Перахват", "Feathergrip", 1.00, 1.00, 1.00, false, "Щекотно и больно.");
        sink.add("perchling", "minecraft:parrot", "legs", "", "Жердочник", "Perchling", 1.00, 1.20, 1.00, false, "Цепляется за любую ветку.");
        sink.add("plumebod", "minecraft:parrot", "torso", "", "Перотело", "Plumebod", 1.00, 1.00, 1.00, false, "Оперение шуршит, как страницы книги.");
        sink.add("thumpkin", "minecraft:rabbit", "head", "", "Топотун", "Thumpkin", 1.00, 1.40, 1.00, false, "Стучит лапами из-под плиты.");
        sink.add("thumpfists", "minecraft:rabbit", "arms", "", "Топот-кулаки", "Thumpfists", 1.00, 1.00, 1.00, false, "Бьёт лапой наотмашь.");
        sink.add("hoppyghast", "minecraft:rabbit", "legs", "", "Прыгун-призрак", "Hoppyghast", 1.00, 1.50, 1.00, false, "Скачет выше забора кладбища.");
        sink.add("softdown", "minecraft:rabbit", "torso", "", "Пухотело", "Softdown", 1.00, 1.00, 1.00, false, "Мягкий подшёрсток быстрой жертвы.");
        sink.add("marshcroaker", "minecraft:frog", "head", "", "Топотун топей", "Marshcroaker", 1.00, 1.10, 1.00, false, "Квакает на болотах душ.");
        sink.add("stickytoes", "minecraft:frog", "arms", "", "Липкопальцы", "Stickytoes", 1.00, 1.00, 1.00, false, "Присоски на костяшках.");
        sink.add("leaper", "minecraft:frog", "legs", "", "Прыткотоп", "Leaper", 1.00, 1.40, 1.00, false, "Лягушачий прыжок в вечность.");
        sink.add("mudbelly", "minecraft:frog", "torso", "", "Грязепуз", "Mudbelly", 1.00, 1.00, 1.00, false, "Влажное брюхо, надувающееся перед прыжком.");
        sink.add("caravangul", "minecraft:camel", "head", "", "Каравангуль", "Caravangul", 1.50, 1.10, 1.00, false, "Везёт караван из преисподней.");
        sink.add("humpguard", "minecraft:camel", "arms", "", "Горбохват", "Humpguard", 1.50, 1.00, 1.00, false, "Держится за горб крепко.");
        sink.add("dunestrider", "minecraft:camel", "legs", "", "Дюноход", "Dunestrider", 1.00, 1.40, 1.00, false, "Идёт по барханам забвения.");
        sink.add("humpside", "minecraft:camel", "torso", "", "Горбобок", "Humpside", 1.50, 1.00, 1.00, false, "Горбы полны воды для долгого пути.");
        sink.add("gravehunter", "minecraft:sniffer", "head", "", "Могильный пёс", "Gravehunter", 1.00, 1.10, 1.00, false, "Чует семена древних кладбищ.");
        sink.add("snoutdigger", "minecraft:sniffer", "arms", "", "Нюхокоп", "Snoutdigger", 1.00, 1.00, 1.00, false, "Роет носом и руками.");
        sink.add("rootsnatcher", "minecraft:sniffer", "legs", "", "Корнеед", "Rootsnatcher", 1.00, 1.10, 1.00, false, "Вынюхивает корни под плитой.");
        sink.add("rootfur", "minecraft:sniffer", "torso", "", "Корнешерсть", "Rootfur", 1.00, 1.00, 1.00, false, "Шерсть, спутанная с корнями древних трав.");
        sink.add("dustwight", "minecraft:husk", "head", "", "Пылепризрак", "Dustwight", 1.00, 1.00, 1.00, true, "Высох в песках времени.");
        sink.add("sandgrip", "minecraft:husk", "arms", "", "Пескохват", "Sandgrip", 1.00, 1.00, 1.00, true, "Сушит кожу одним касанием.");
        sink.add("dusttreader", "minecraft:husk", "legs", "", "Пылемер", "Dusttreader", 1.00, 1.10, 1.00, true, "Шаг — и песок шепчет имя.");
        sink.add("deshide", "minecraft:husk", "torso", "", "Пустынкошкура", "Deshide", 1.00, 1.00, 1.00, true, "Кожа, дублёная песком и солнцем.");
        sink.add("brinewight", "minecraft:drowned", "head", "", "Солончег", "Brinewight", 1.00, 1.00, 1.00, false, "Пропитан морской солью и тлением.");
        sink.add("webhand", "minecraft:drowned", "arms", "", "Сетерук", "Webhand", 1.00, 1.00, 1.00, false, "Скользок, как угорь.");
        sink.add("kelpshanks", "minecraft:drowned", "legs", "", "Водорослег", "Kelpshanks", 1.00, 1.10, 1.00, false, "Пахнут тиной и могилой.");
        sink.add("kelpbelly", "minecraft:drowned", "torso", "", "Водорослебрюх", "Kelpbelly", 1.00, 1.00, 1.00, false, "Живот, обросший подводной травой.");
        sink.add("frostbone", "minecraft:stray", "head", "", "Инеекость", "Frostbone", 1.00, 1.00, 1.00, false, "Стреляет инеем из-за могилы.");
        sink.add("frostgrip", "minecraft:stray", "arms", "", "Инехват", "Frostgrip", 1.00, 1.00, 1.00, false, "Рукавичка из инея.");
        sink.add("iceshanks", "minecraft:stray", "legs", "", "Леденог", "Iceshanks", 1.00, 1.10, 1.00, false, "Хрустят, как наст.");
        sink.add("frostpelt", "minecraft:stray", "torso", "", "Инешкура", "Frostpelt", 1.00, 1.00, 1.00, false, "Шкура, покрытая изморозью.");
        sink.add("packdead", "minecraft:mule", "head", "", "Пакорок", "Packdead", 1.00, 1.00, 1.00, false, "Вьючное животное загроба.");
        sink.add("packreach", "minecraft:mule", "arms", "", "Вьюкорук", "Packreach", 1.00, 1.00, 1.00, false, "Натянет вьюк на кого угодно.");
        sink.add("burdenbeast", "minecraft:mule", "legs", "", "Тяглек", "Burdenbeast", 1.00, 1.10, 1.00, false, "Несёт ношу мёртвых.");
        sink.add("packsaddle", "minecraft:mule", "torso", "", "Вьюкож", "Packsaddle", 1.00, 1.00, 1.00, false, "Спина, помнящая вьюки.");
        sink.add("millergul", "minecraft:donkey", "head", "", "Мельник", "Millergul", 1.00, 1.00, 1.00, false, "Мелет кости в муку.");
        sink.add("quernarm", "minecraft:donkey", "arms", "", "Жерноворук", "Quernarm", 1.00, 1.00, 1.00, false, "Крутит жернова из костей.");
        sink.add("panniershade", "minecraft:donkey", "legs", "", "Понузник", "Panniershade", 1.00, 1.10, 1.00, false, "Вьюки полны костей.");
        sink.add("millhide", "minecraft:donkey", "torso", "", "Мельничная кожа", "Millhide", 1.00, 1.00, 1.00, false, "Шкура, пропахшая мукой и костной пылью.");
        sink.add("woolphantom", "minecraft:llama", "head", "", "Шерстофантом", "Woolphantom", 1.00, 1.00, 1.00, false, "Плевётся призрачной шерстью.");
        sink.add("spitguard", "minecraft:llama", "arms", "", "Плевок", "Spitguard", 1.00, 1.00, 1.00, false, "Плюёт наглой слюной.");
        sink.add("caravanstep", "minecraft:llama", "legs", "", "Караванный шаг", "Caravanstep", 1.00, 1.10, 1.00, false, "Идёт вереницей за горизонт.");
        sink.add("woolmass", "minecraft:llama", "torso", "", "Шерстогруз", "Woolmass", 1.00, 1.00, 1.00, false, "Клубок шерсти, что несёт ношу.");
        sink.add("bazaarwraith", "minecraft:trader_llama", "head", "", "Базарный призрак", "Bazaarwraith", 1.00, 1.00, 1.00, false, "Торгует редкостями мертвецов.");
        sink.add("bellsleeve", "minecraft:trader_llama", "arms", "", "Бубенец", "Bellsleeve", 1.00, 1.00, 1.00, false, "Рукав с бубенцами идущего каравана.");
        sink.add("peddler", "minecraft:trader_llama", "legs", "", "Холак", "Peddler", 1.00, 1.20, 1.00, false, "Разносит товар меж миров.");
        sink.add("saddleside", "minecraft:trader_llama", "torso", "", "Седлобок", "Saddleside", 1.00, 1.00, 1.00, false, "Бока, отёртые купеческим седлом.");
        sink.add("icepaw", "minecraft:polar_bear", "head", "", "Ледопал", "Icepaw", 1.50, 1.00, 1.50, false, "Хищник белых пустошей.");
        sink.add("sealfist", "minecraft:polar_bear", "arms", "", "Тюленекулак", "Sealfist", 1.00, 1.00, 1.50, false, "Бьёт лапой, как об лёд.");
        sink.add("floetracker", "minecraft:polar_bear", "legs", "", "Ледоход", "Floetracker", 1.00, 1.20, 1.00, false, "Ходит по тонкой корке могил.");
        sink.add("blizzardcoat", "minecraft:polar_bear", "torso", "", "Буранник", "Blizzardcoat", 1.50, 1.00, 1.00, false, "Шкура, сшитая из метели.");
        sink.add("goldghast", "minecraft:piglin", "head", "", "Златожаба", "Goldghast", 1.00, 1.00, 1.50, false, "Жадность пережила смерть.");
        sink.add("goldcuff", "minecraft:piglin", "arms", "", "Златоноша", "Goldcuff", 1.00, 1.00, 1.50, false, "Наручи из слитков.");
        sink.add("coinrunner", "minecraft:piglin", "legs", "", "Монетоход", "Coinrunner", 1.00, 1.20, 1.00, false, "Бегает за золотом в ад.");
        sink.add("giltbelly", "minecraft:piglin", "torso", "", "Златобрюх", "Giltbelly", 1.00, 1.00, 1.00, false, "Пузо, отполированное монетами.");
        sink.add("bruteshade", "minecraft:piglin_brute", "head", "", "Отверженный", "Bruteshade", 1.50, 1.00, 2.00, false, "Кулак, который не гнётся.");
        sink.add("axearm", "minecraft:piglin_brute", "arms", "", "Секирорука", "Axearm", 1.50, 1.00, 2.00, false, "Одна рука — один удар.");
        sink.add("banishedpace", "minecraft:piglin_brute", "legs", "", "Ссылбег", "Banishedpace", 1.00, 1.20, 1.00, false, "Бежит туда, откуда не возвращаются.");
        sink.add("brutemail", "minecraft:piglin_brute", "torso", "", "Грубоброня", "Brutemail", 1.50, 1.00, 1.50, false, "Кожаный панцирь арены.");
        sink.add("tuskfiend", "minecraft:hoglin", "head", "", "Клыкостраф", "Tuskfiend", 1.50, 1.10, 1.50, false, "Рыщет по багровым лесам.");
        sink.add("tuskgrip", "minecraft:hoglin", "arms", "", "Клыкохват", "Tuskgrip", 1.00, 1.00, 1.50, false, "Загнул клыки на руки.");
        sink.add("rooter", "minecraft:hoglin", "legs", "", "Корнебой", "Rooter", 1.00, 1.20, 1.00, false, "Выворачивает землю копытом.");
        sink.add("truffleskin", "minecraft:hoglin", "torso", "", "Трюфелешкур", "Truffleskin", 1.50, 1.00, 1.00, false, "Кожа, пропахшая подземными грибами.");
        sink.add("rotstalker", "minecraft:zoglin", "head", "", "Гнилоход", "Rotstalker", 1.50, 1.10, 1.50, false, "Зомбированный кабан ада.");
        sink.add("rotclaw", "minecraft:zoglin", "arms", "", "Гнилокоготь", "Rotclaw", 1.00, 1.00, 1.50, false, "Царапает до лихорадки.");
        sink.add("rottrotter", "minecraft:zoglin", "legs", "", "Гнилобег", "Rottrotter", 1.00, 1.30, 1.00, false, "Бежит, оставляя вонь.");
        sink.add("putridheave", "minecraft:zoglin", "torso", "", "Смердосвал", "Putridheave", 1.50, 1.00, 1.00, false, "Туша, от которой стелется смрад.");
        sink.add("emberbaron", "minecraft:zombified_piglin", "head", "", "Угольный барон", "Emberbaron", 1.50, 1.00, 1.50, true, "Держит суд над угольем.");
        sink.add("embergauntlet", "minecraft:zombified_piglin", "arms", "", "Угольная рукавица", "Embergauntlet", 1.00, 1.00, 1.50, true, "Рукавица из углей.");
        sink.add("emberstrider", "minecraft:zombified_piglin", "legs", "", "Уголовник", "Emberstrider", 1.00, 1.10, 1.00, true, "Идёт по углям, как по траве.");
        sink.add("scorchbelly", "minecraft:zombified_piglin", "torso", "", "Подчрево", "Scorchbelly", 1.50, 1.00, 1.00, true, "Брюхо, запечённое в аду.");
        sink.add("charredlord", "minecraft:wither_skeleton", "head", "", "Обугленный лорд", "Charredlord", 1.50, 1.00, 2.00, true, "Лорд иссушенных земель.");
        sink.add("withergrasp", "minecraft:wither_skeleton", "arms", "", "Иссухохват", "Withergrasp", 1.50, 1.00, 2.00, true, "Касание — иссушение.");
        sink.add("ashwalker", "minecraft:wither_skeleton", "legs", "", "Пепелеход", "Ashwalker", 1.00, 1.10, 1.00, true, "Не оставляет следа на пепле.");
        sink.add("charribone", "minecraft:wither_skeleton", "torso", "", "Углекость", "Charribone", 1.50, 1.00, 1.50, true, "Рёбра, обугленные в адовых печах.");
        sink.add("rimeguard", "minecraft:snow_golem", "head", "", "Инейный страж", "Rimeguard", 1.00, 1.00, 1.00, false, "Страж снежных склепов.");
        sink.add("snowfling", "minecraft:snow_golem", "arms", "", "Снежнелёт", "Snowfling", 1.00, 1.00, 1.00, false, "Метает комья вечной мерзлоты.");
        sink.add("driftwalker", "minecraft:snow_golem", "legs", "", "Снегоброд", "Driftwalker", 1.00, 1.10, 1.00, false, "Оставляет след из изморози.");
        sink.add("slushcore", "minecraft:snow_golem", "torso", "", "Слякотяж", "Slushcore", 1.00, 1.00, 1.00, false, "Сердцевина из тающего снега.");
        sink.add("titanmaw", "minecraft:giant", "head", "", "Титанья пасть", "Titanmaw", 2.00, 1.00, 2.00, false, "Челюсти забытого исполина.");
        sink.add("colossusfist", "minecraft:giant", "arms", "", "Кулак колосса", "Colossusfist", 2.00, 1.00, 2.00, false, "Один мах — и поля нет.");
        sink.add("earthtreader", "minecraft:giant", "legs", "", "Земеход", "Earthtreader", 2.00, 0.90, 1.50, false, "Тяжёлая поступь великанов.");
        sink.add("atlasbulk", "minecraft:giant", "torso", "", "Атлантело", "Atlasbulk", 2.00, 1.00, 1.50, false, "Плечи, держащие свод мира.");
        sink.add("dreamhaunt", "minecraft:phantom", "head", "", "Сновидец", "Dreamhaunt", 1.00, 1.20, 1.00, false, "Прилетает к тем, кто не спит.");
        sink.add("membraneclutch", "minecraft:phantom", "arms", "", "Перепонкохват", "Membraneclutch", 1.00, 1.00, 1.00, false, "Обвивает пергаментом кожи.");
        sink.add("hoverling", "minecraft:phantom", "legs", "", "Левитант", "Hoverling", 1.00, 1.30, 1.00, false, "Едва касается земли.");
        sink.add("lochloma", "minecraft:phantom", "torso", "", "Лохлома", "Lochloma", 1.00, 1.00, 1.00, false, "Плащ из обрывков крыльев.");
        sink.add("plaguelord", "minecraft:zombie_villager", "head", "", "Чумной лорд", "Plaguelord", 1.50, 1.00, 1.50, false, "Носитель мора среди живых.");
        sink.add("plagueclasp", "minecraft:zombie_villager", "arms", "", "Чумозахват", "Plagueclasp", 1.00, 1.00, 1.00, false, "Пожатие руки с мором.");
        sink.add("plaguewalker", "minecraft:zombie_villager", "legs", "", "Чумоход", "Plaguewalker", 1.00, 1.10, 1.00, false, "Где пройдёт — трава не растёт.");
        sink.add("plaguecoat", "minecraft:zombie_villager", "torso", "", "Чумеплащ", "Plaguecoat", 1.00, 1.00, 1.00, false, "Подол, пропахший чумой.");
        sink.add("silvermote", "minecraft:silverfish", "head", "", "Сребропыль", "Silvermote", 1.00, 1.20, 1.00, false, "Шуршит в стенах гробниц.");
        sink.add("silverfingers", "minecraft:silverfish", "arms", "", "Серебропальцы", "Silverfingers", 1.00, 1.00, 1.00, false, "Тонкие, как проволока.");
        sink.add("wallcrawler", "minecraft:silverfish", "legs", "", "Стенолаз", "Wallcrawler", 1.00, 1.40, 1.00, false, "Ползёт туда, где нет пола.");
        sink.add("bristleback", "minecraft:silverfish", "torso", "", "Щетиноспин", "Bristleback", 1.00, 1.00, 1.00, false, "Спина, дыбящаяся от света.");
        sink.add("voidling", "minecraft:endermite", "head", "", "Пустотник", "Voidling", 1.00, 1.20, 1.00, false, "Рождён из трещины между мирами.");
        sink.add("voidwrithing", "minecraft:endermite", "arms", "", "Пустотокрут", "Voidwrithing", 1.00, 1.00, 1.00, false, "Извивается без костей.");
        sink.add("crackskitter", "minecraft:endermite", "legs", "", "Щелевик", "Crackskitter", 1.00, 1.30, 1.00, false, "Шмыгает по трещинам пространства.");
        sink.add("chitinbelly", "minecraft:endermite", "torso", "", "Хитинобок", "Chitinbelly", 1.00, 1.00, 1.00, false, "Брюшко, звенящее, как стекло.");
        sink.add("tormented", "minecraft:vex", "head", "", "Мучник", "Tormented", 1.00, 1.30, 1.00, false, "Душа, не нашедшая покоя.");
        sink.add("razorwing", "minecraft:vex", "arms", "", "Бритвокрыл", "Razorwing", 1.00, 1.00, 1.50, false, "Крылья режут воздух.");
        sink.add("flitstep", "minecraft:vex", "legs", "", "Мельтоток", "Flitstep", 1.00, 1.40, 1.00, false, "Мелькает, не касаясь опоры.");
        sink.add("gauzewrap", "minecraft:vex", "torso", "", "Марлевик", "Gauzewrap", 1.00, 1.00, 1.00, false, "Пелена, ставшая плотью.");
        sink.add("hexbinder", "minecraft:evoker", "head", "", "Плетун", "Hexbinder", 1.00, 1.00, 1.00, false, "Завязывает судьбы в узлы.");
        sink.add("fangsummoner", "minecraft:evoker", "arms", "", "Клыкорождающий", "Fangsummoner", 1.00, 1.00, 1.00, false, "Вызывает зубы из земли.");
        sink.add("ritualist", "minecraft:evoker", "legs", "", "Ритуалист", "Ritualist", 1.00, 1.10, 1.00, false, "Вышагивает круги заклинаний.");
        sink.add("robebody", "minecraft:evoker", "torso", "", "Мантиятело", "Robebody", 1.00, 1.00, 1.00, false, "Мантия, что носит сама себя.");
        sink.add("cleaver", "minecraft:vindicator", "head", "", "Тесак", "Cleaver", 1.00, 1.00, 2.00, false, "Один удар — и имени нет.");
        sink.add("butcherarm", "minecraft:vindicator", "arms", "", "Мясорук", "Butcherarm", 1.00, 1.00, 2.00, false, "Рубит топором наотмашь.");
        sink.add("axefoot", "minecraft:vindicator", "legs", "", "Секироног", "Axefoot", 1.00, 1.20, 1.00, false, "Подходит вплотную быстро.");
        sink.add("axeback", "minecraft:vindicator", "torso", "", "Топотоспин", "Axeback", 1.00, 1.00, 1.00, false, "Спина, натёртая рукоятью.");
        sink.add("mirage", "minecraft:illusioner", "head", "", "Мираж", "Mirage", 1.00, 1.10, 1.00, false, "Обман зрячих и мёртвых.");
        sink.add("miragehands", "minecraft:illusioner", "arms", "", "Миражоруки", "Miragehands", 1.00, 1.00, 1.00, false, "Руки-обманки.");
        sink.add("fakewalk", "minecraft:illusioner", "legs", "", "Ходообман", "Fakewalk", 1.00, 1.00, 1.00, false, "Идёт, но следов не видно.");
        sink.add("mirrorcoat", "minecraft:illusioner", "torso", "", "Зеркалка", "Mirrorcoat", 1.00, 1.00, 1.00, false, "Кафтан, отражающий лишних.");
        sink.add("marauder", "minecraft:pillager", "head", "", "Мародёр", "Marauder", 1.00, 1.00, 1.00, false, "Грабит даже могилы.");
        sink.add("crossbowarm", "minecraft:pillager", "arms", "", "Арбалторук", "Crossbowarm", 1.00, 1.00, 1.00, false, "Рука-станок.");
        sink.add("raidstepper", "minecraft:pillager", "legs", "", "Рейдер", "Raidstepper", 1.00, 1.10, 1.00, false, "Шаги набега на деревню.");
        sink.add("captainside", "minecraft:pillager", "torso", "", "Капитанбок", "Captainside", 1.00, 1.00, 1.00, false, "Наградной кафтан рейдера.");
        sink.add("behemoth", "minecraft:ravager", "head", "", "Левиафан", "Behemoth", 2.00, 1.00, 2.00, false, "Хребтолом, идущий сквозь строй.");
        sink.add("lobberfist", "minecraft:ravager", "arms", "", "Таранорука", "Lobberfist", 2.00, 1.00, 2.00, false, "Сносит стену с разбега.");
        sink.add("siegebreaker", "minecraft:ravager", "legs", "", "Стенобой", "Siegebreaker", 2.00, 1.00, 1.50, false, "Ломит ворота одним весом.");
        sink.add("ramsided", "minecraft:ravager", "torso", "", "Таранобок", "Ramsided", 2.00, 1.00, 1.00, false, "Грудь, что идёт сквозь частокол.");
        sink.add("doomcaller", "minecraft:warden", "head", "", "Зовущий рок", "Doomcaller", 2.00, 1.00, 2.00, false, "Слышит биение сердец из-за стены.");
        sink.add("sonicmaul", "minecraft:warden", "arms", "", "Звукобой", "Sonicmaul", 2.00, 1.00, 2.00, false, "Бьёт звуком.");
        sink.add("deepstrider", "minecraft:warden", "legs", "", "Глубиноход", "Deepstrider", 2.00, 1.00, 1.50, false, "Идёт сквозь скалу.");
        sink.add("sculkbod", "minecraft:warden", "torso", "", "Скалкобрюх", "Sculkbod", 2.00, 1.00, 1.00, false, "Тело, проросшее скалком.");
        sink.add("galewight", "minecraft:breeze", "head", "", "Ветреник", "Galewight", 1.00, 1.30, 1.00, false, "Прыгучий сквозняк из ниоткуда.");
        sink.add("windlass", "minecraft:breeze", "arms", "", "Ветротвод", "Windlass", 1.00, 1.00, 1.00, false, "Крутит ветер, как лебёдку.");
        sink.add("galehopper", "minecraft:breeze", "legs", "", "Сквозняк", "Galehopper", 1.00, 1.50, 1.00, false, "Прыжки по потокам ветра.");
        sink.add("draftcore", "minecraft:breeze", "torso", "", "Сквозносердие", "Draftcore", 1.00, 1.00, 1.00, false, "В груди гуляет северный ветер.");
        sink.add("ichorling", "minecraft:slime", "head", "", "Ихорник", "Ichorling", 1.00, 1.10, 1.00, false, "Слизь, что помнит своего хозяина.");
        sink.add("gooeygrip", "minecraft:slime", "arms", "", "Липкорук", "Gooeygrip", 1.00, 1.00, 1.00, false, "Прилипнешь — не отклеишься.");
        sink.add("bounceghast", "minecraft:slime", "legs", "", "Скакуша", "Bounceghast", 1.00, 1.30, 1.00, false, "Подпрыгивает к горлу.");
        sink.add("globbelly", "minecraft:slime", "torso", "", "Лопхеуз", "Globbelly", 1.00, 1.00, 1.00, false, "Пузырь, что держит форму.");
        sink.add("magmaling", "minecraft:magma_cube", "head", "", "Магмалинг", "Magmaling", 1.00, 1.00, 1.50, true, "Искра бездны в луже смолы.");
        sink.add("tarclutch", "minecraft:magma_cube", "arms", "", "Смологрыз", "Tarclutch", 1.00, 1.00, 1.50, true, "Хватает смолой.");
        sink.add("cinderhops", "minecraft:magma_cube", "legs", "", "Искроскок", "Cinderhops", 1.00, 1.20, 1.00, true, "Капля лавы в человеческий рост.");
        sink.add("tarbod", "minecraft:magma_cube", "torso", "", "Смоложоп", "Tarbod", 1.00, 1.00, 1.00, true, "Смоляной бок, липкий и жаркий.");
        sink.add("skyreaver", "minecraft:ghast", "head", "", "Небесный жилец", "Skyreaver", 1.50, 1.00, 1.50, true, "Плачет огнём с низких сводов.");
        sink.add("tentaclewhip", "minecraft:ghast", "arms", "", "Щупалка-хлыст", "Tentaclewhip", 1.00, 1.00, 1.50, true, "Хлещет девятью хлыстами.");
        sink.add("cloudtreader", "minecraft:ghast", "legs", "", "Облакомер", "Cloudtreader", 1.00, 1.20, 1.00, true, "Ступает по облакам пепла.");
        sink.add("membranous", "minecraft:ghast", "torso", "", "Перепончатый", "Membranous", 1.50, 1.00, 1.00, true, "Белое брюхо, парящее под сводом.");
        sink.add("boxlich", "minecraft:shulker", "head", "", "Лич-ларец", "Boxlich", 1.50, 1.00, 1.00, false, "Сундук, который кусается первым.");
        sink.add("levitationclasp", "minecraft:shulker", "arms", "", "Левитозахват", "Levitationclasp", 1.00, 1.00, 1.00, false, "Поднимает в воздух.");
        sink.add("chestcrawler", "minecraft:shulker", "legs", "", "Сундукополз", "Chestcrawler", 1.00, 0.90, 1.00, false, "Волочит панцирь по ступеням.");
        sink.add("endershell", "minecraft:shulker", "torso", "", "Эндощит", "Endershell", 1.50, 1.00, 1.00, false, "Коробка из эндер-дерева.");
        sink.add("pricklefin", "minecraft:guardian", "head", "", "Колючепёр", "Pricklefin", 1.50, 1.00, 1.00, false, "Лучевик затонших храмов.");
        sink.add("laserpincher", "minecraft:guardian", "arms", "", "Лучехват", "Laserpincher", 1.00, 1.00, 1.00, false, "Заряжается и бьёт.");
        sink.add("reefwalker", "minecraft:guardian", "legs", "", "Рифоход", "Reefwalker", 1.00, 1.00, 1.00, false, "Идёт по дну мёртвого рифа.");
        sink.add("prismabulk", "minecraft:guardian", "torso", "", "Призмобрюх", "Prismabulk", 1.50, 1.00, 1.00, false, "Тело из морского стекла.");
        sink.add("deepbishop", "minecraft:elder_guardian", "head", "", "Глубинный архиерей", "Deepbishop", 2.00, 0.90, 1.50, false, "Благословляет трепетом.");
        sink.add("mininggrip", "minecraft:elder_guardian", "arms", "", "Киркохват", "Mininggrip", 1.50, 1.00, 1.00, false, "Ослабляет броню взглядом.");
        sink.add("abysspad", "minecraft:elder_guardian", "legs", "", "Бездонная лапа", "Abysspad", 2.00, 0.80, 1.00, false, "Тянет на дно одним взглядом.");
        sink.add("ancientside", "minecraft:elder_guardian", "torso", "", "Древнебок", "Ancientside", 2.00, 1.00, 1.00, false, "Бока, покрытые наростами веков.");
    }
}
